        apiVersion: apps/v1
        kind: Deployment
        metadata:
          namespace: whoami
          labels:
            app: whoami
          name: whoami
        spec:
          replicas: 5
          selector:
            matchLabels:
              app: whoami
          template:
            metadata:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/path: /metrics
                prometheus.io/port: "80"
              labels:
                app: whoami
            spec:
              containers:
                - image: traefik/whoami:latest
                  name: whoami
                  ports:
                    - name: whoami
                      containerPort: 80
---
        apiVersion: v1
        kind: Service
        metadata:
          namespace: whoami
          name: whoami-svc
        spec:
          ports:
          - name: http
            targetPort: 80
            port: 80
          selector:
            app: whoami
