        kind: Deployment
        apiVersion: apps/v1
        metadata:
          namespace: blue      
          name: blue-deploy
          labels:
            app: blue
        spec:
          replicas: 7
          selector:
            matchLabels:
              app: blue
          template:
            metadata:
              labels:
                app: blue
            spec:
              containers:
              - name: blue
                image: kubedevio/nginx-color:green
                ports:
                - containerPort: 80
---
        apiVersion: v1
        kind: Service
        metadata:
          namespace: blue
          name: blue-service
        spec:
          ports:
            - port: 80
              targetPort: 80
          selector:
            app: blue
---
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          namespace: blue
          name: blue-ingress
        spec:
          rules:
          - host: blue.traefik.189.7.79.10.nip.io
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                       name: blue-service
                       port:
                        number: 80
