        kind: Deployment
        apiVersion: apps/v1
        metadata:
          namespace: frontend
          name: breaktest-deploy
          labels:
            app: breaktest
        spec:
          replicas: 5
          selector:
            matchLabels:
              app: breaktest
          template:
            metadata:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/path: /metrics
                prometheus.io/port: "3000"            
              labels:
                app: breaktest
            spec:
              containers:
              - name: breaktest
                image: nilozjr/testeapi:v3
                resources:
                  requests:
                    memory: "32Mi"
                    cpu: "100m"
                  limits:
                    memory: "64Mi"
                    cpu: "500m"
                command:
                  - "/consumer"
                  - -port
                  - "3000"                
                ports:
                - containerPort: 3000
---
        apiVersion: v1
        kind: Service
        metadata:
          namespace: frontend
          name: breaktest-svc
        spec:
          ports:
            - port: 80
              targetPort: 3000
          selector:
