        kind: Deployment
        apiVersion: apps/v1
        metadata:
          namespace: erro
          name: erro-deploy
          labels:
            app: erro
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: erro
          template:
            metadata:
              labels:
                app: erro
            spec:
              containers:
              - name: erro
                image: nilozjr/testeapi:v3
                resources:
                  requests:
                    memory: "32Mi"
                    cpu: "100m"
                  limits:
                    memory: "64Mi"
                    cpu: "500m"
                ports:
                - containerPort: 3000
                livenessProbe:
                httpGet:
                    path: /healthz
                    port: 3000
                initialDelaySeconds: 15
                periodSeconds: 15
                failureThreshold: 2
