        kind: Deployment
        apiVersion: apps/v1
        metadata:
          namespace: blue
          name: resource-deploy
          labels:
            app: resource
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: resource
          template:
            metadata:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/path: /metrics
                prometheus.io/port: "8080"
              labels:
                app: resource
            spec:
              containers:
              - name: resource
                image: gcr.io/kubernetes-e2e-test-images/resource-consumer:1.5
                resources:
                  requests:
                    memory: "32Mi"
                    cpu: "100m"
                  limits:
                    memory: "64Mi"
                    cpu: "500m"
                command:
                  - "/consumer"
                  - -port
                  - "8080"
                ports:
                - containerPort: 8080
---
        apiVersion: v1
        kind: Service
        metadata:
          namespace: blue
          name: resource-svc
        spec:
          ports:
            - port: 80
              targetPort: 8080
          selector:
            app: resource
